# Generated by Django 5.0.7 on 2024-08-23 05:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_alter_subscription_shared_to"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="shared_to",
            field=models.ManyToManyField(
                blank=True,
                related_name="shared_subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
