# Generated by Django 5.0.7 on 2024-08-23 05:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_alter_subscription_shared_to"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="community_members",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
