# Generated by Django 5.0.7 on 2024-09-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_invite"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("book", "Book"),
                    ("electronics", "Electronics"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
