# Generated by Django 5.1.1 on 2024-09-19 04:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0004_item_item_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="invite_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
