# Generated by Django 5.1.1 on 2024-09-19 04:28

import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    Community = apps.get_model("backend", "Community")
    for row in Community.objects.all():
        row.invite_uuid = uuid.uuid4()
        row.save(update_fields=["invite_uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_community_invite_uuid"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
