# Generated by Django 5.1.1 on 2024-09-19 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_auto_20240919_0439"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Invite",
        ),
    ]
