# Generated by Django 5.1.1 on 2024-09-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0006_delete_invite"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True, related_name="shared_items", to="backend.community"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True, related_name="shared_subscriptions", to="backend.community"
            ),
        ),
    ]
